board_members_years = [
    {
        "year_start": "2024",
        "year_end": "2025",
        "voorzitter": "J. Maaskant",
        "vicevoorzitter": "G. v. d. Sluis",
        "penningmeester": "T. Lasschuit",
        "famous_quote": "Trek een bak",
        "main_image": {"url": "../img/besturen/bestuur_2024.png", "alt": "Bestuur 2024 - 2025",
                       "size": "576x575"},
    },
    {
        "year_start": "2023",
        "year_end": "2024",
        "voorzitter": "S. K. Heerenbrink",
        "vicevoorzitter": "D. Hidding",
        "penningmeester": "T. Lasschuit",
        "famous_quote": "Trek een bak",
        "main_image": {"url": "../img/besturen/bestuur_2023.png", "alt": "Bestuur 2023 - 2024", "size": "576x575"},
    },
    {
        "year_start": "2022",
        "year_end": "2023",
        "voorzitter": "M. Lindt",
        "vicevoorzitter": "M. Hermens",
        "penningmeester": "K. Severijns",
        "famous_quote": "Trek een bak",
        "main_image": {"url": "../img/besturen/bestuur_2022.png", "alt": "Bestuur 2022 - 2023", "size": "576x575"},
    },
    {
        "year_start": "2021",
        "year_end": "2022",
        "voorzitter": "Q. D. Wessels",
        "vicevoorzitter": "A. D. Nederlanden",
        "penningmeester": "M. Crijns",
        "famous_quote": "Studeren doe je voor even maar Aether is voor het leven",
        "main_image": {"url": "../img/besturen/bestuur_2020.png", "alt": "Bestuur 2021 - 2022", "size": "576x575"},
    },
    {
        "year_start": "2020",
        "year_end": "2021",
        "voorzitter": "Q. D. Wessels",
        "vicevoorzitter": "A. D. Nederlanden",
        "penningmeester": "M. Crijns",
        "famous_quote": "Ook op afstand blijft het gezellig (corona jaar)",
        "main_image": {"url": "../img/besturen/bestuur_2020.png", "alt": "Bestuur 2020 - 2021", "size": "576x575"},
    },
    {
        "year_start": "2019",
        "year_end": "2020",
        "voorzitter": "Q. D. Wessels",
        "vicevoorzitter": None,
        "penningmeester": None,
        "famous_quote": "Lone wolf",
        "main_image": {"url": "../img/besturen/bestuur_2019.png", "alt": "Bestuur 2019 - 2020", "size": "576x575"},
    },
    {
        "year_start": "2018",
        "year_end": "2019",
        "voorzitter": "F. Soffers",
        "vicevoorzitter": "D. Neijenhuis",
        "penningmeester": "",
        "famous_quote": "Aether Deus Ex Machina",
        "main_image": {"url": "../img/besturen/bestuur_2018.png", "alt": "Bestuur 2018 - 2019", "size": "576x575"},
    },
]