board_members_years = [
    {
        "year_start": "2024",
        "year_end": "2025",
        "voorzitter": "Voorzitter",
        "vicevoorzitter": "Vicevoorzitter",
        "penningmeester": "Penningmeester",
        "famous_quote": "Kei mooi jaar jonguh",
        "main_image": {"url": "../img/besturen/main_bestuur_comingsoon.png", "alt": " Main Image 1 Alt Text",
                       "size": "576x575"},
    },
    {
        "year_start": "2023",
        "year_end": "2024",
        "voorzitter": "Jan Jansen",
        "vicevoorzitter": "Kees Mulder",
        "penningmeester": "Sjaak Sjakeer",
        "famous_quote": "Kei mooi jaar jonguh",
        "main_image": {"url": "../img/besturen/main_bestuur.png", "alt": " Main Image 1 Alt Text", "size": "576x575"},
    },
    {
        "year_start": "2022",
        "year_end": "2023",
        "voorzitter": "L | Jan Jansen",
        "vicevoorzitter": "M |Kees Mulder",
        "penningmeester": "R | Sjaak Sjakeer",
        "famous_quote": "Kei mooi jaar jonguh",
        "main_image": {"url": "../img/besturen/main_bestuur_2022.png", "alt": " Main Image 1 Alt Text", "size": "576x575"},
    },
    {
        "year_start": "2021",
        "year_end": "2022",
        "voorzitter": "Voorzitter",
        "vicevoorzitter": "Vicevoorzitter",
        "penningmeester": "Penningmeester",
        "famous_quote": "Kei mooi jaar jonguh",
        "main_image": {"url": "../img/besturen/main_bestuur_comingsoon.png", "alt": " Main Image 1 Alt Text", "size": "576x575"},
    },
    {
        "year_start": "2020",
        "year_end": "2021",
        "voorzitter": "Voorzitter",
        "vicevoorzitter": "Vicevoorzitter",
        "penningmeester": "Penningmeester",
        "famous_quote": "Kei mooi jaar jonguh",
        "main_image": {"url": "../img/besturen/main_bestuur_comingsoon.png", "alt": " Main Image 1 Alt Text", "size": "576x575"},
    },
    {
        "year_start": "2019",
        "year_end": "2020",
        "voorzitter": "Q. D. W.",
        "vicevoorzitter": None,
        "penningmeester": None,
        "famous_quote": "Kei mooi jaar jonguh",
        "main_image": {"url": "../img/besturen/main_bestuur_comingsoon.png", "alt": " Main Image 1 Alt Text", "size": "576x575"},
    },
    {
        "year_start": "2018",
        "year_end": "2019",
        "voorzitter": "Voorzitter",
        "vicevoorzitter": "Vicevoorzitter",
        "penningmeester": "Penningmeester",
        "famous_quote": "Kei mooi jaar jonguh",
        "main_image": {"url": "../img/besturen/main_bestuur_comingsoon.png", "alt": " Main Image 1 Alt Text", "size": "576x575"},
    },
]